[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''
    if _center.name == 'Half Joker' and (_center.discovered or self.bypass_discovery_center) then 
        self.children.center.scale.y = self.children.center.scale.y/1.7
    end
    if _center.name == 'Photograph' and (_center.discovered or self.bypass_discovery_center) then 
        self.children.center.scale.y = self.children.center.scale.y/1.2
    end
    if _center.name == 'Square Joker' and (_center.discovered or self.bypass_discovery_center) then 
        self.children.center.scale.y = self.children.center.scale.x
    end
'''
position = "at"
payload = '''
-- replaced
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''
    elseif self.config.center.name == "Half Joker" then
        self.T.h = H*scale/1.7*scale
        self.T.w = W*scale
'''
position = "at"
payload = '''
-- replaced
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''
    elseif self.config.center.name == "Photograph" then 
        self.T.h = H*scale/1.2*scale
        self.T.w = W*scale
    elseif self.config.center.name == "Square Joker" then
        H = W 
        self.T.h = H*scale
        self.T.w = W*scale
'''
position = "at"
payload = '''
-- replaced
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''
    if center.name == "Half Joker" and (center.discovered or self.bypass_discovery_center) then 
        H = H/1.7
        self.T.h = H
    end

    if center.name == "Photograph" and (center.discovered or self.bypass_discovery_center) then 
        H = H/1.2
        self.T.h = H
    end

    if center.name == "Square Joker" and (center.discovered or self.bypass_discovery_center) then 
        H = W
        self.T.h = H
    end
'''
position = "at"
payload = '''
-- replaced
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''
            if _center.name == 'Half Joker' and (_center.discovered or self.bypass_discovery_center) then
                self.children.center.scale.y = self.children.center.scale.y/1.7
            end
            if _center.name == 'Photograph' and (_center.discovered or self.bypass_discovery_center) then
                self.children.center.scale.y = self.children.center.scale.y/1.2
            end
            if _center.name == 'Square Joker' and (_center.discovered or self.bypass_discovery_center) then
                self.children.center.scale.y = self.children.center.scale.x
            end
'''
position = "at"
payload = '''
-- replaced
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/button_callbacks.lua'''
pattern = '''
  local corpus = '123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'..(hook.config.ref_table.extended_corpus and " 0!$&()<>?:{}+-=,.[]_" or '')
'''
position = "after"
payload = '''
if hook.config.ref_table.extended_corpus then
    corpus = corpus .. "'\""
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''cardarea.lua'''
pattern = '''
{n=G.UIT.R, config={align = "cm", maxw = 2}, nodes={
    {n=G.UIT.T, config={text = localize('k_deck'), scale = 0.38, colour = G.C.WHITE, shadow = true}}
}},
'''
position = "after"
payload = '''
{n=G.UIT.R, config={align = "cm", maxw = 2}, nodes={
    {n=G.UIT.T, config={text = localize('k_jrok_powered'), scale = 0.38, colour = G.C.WHITE, shadow = true}}
}},
{n=G.UIT.R, config={align = "cm", maxw = 2}, nodes={
    {n=G.UIT.T, config={text = localize('k_by_jrok'), scale = 0.38, colour = G.C.WHITE, shadow = true}}
}},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/UI_definitions.lua'''
pattern = '''
{n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.4}, nodes={
    {n=G.UIT.T, config={text = localize('b_run_info_2'), scale = 1*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true, focus_args = {button = G.F_GUIDE and 'guide' or 'back', orientation = 'bm'}, func = 'set_button_pip'}}
}}
'''
position = "at"
payload = '''
{n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.4}, nodes={
    {n=G.UIT.T, config={text = localize('b_run_info_2'), scale = 1*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true, focus_args = {button = G.F_GUIDE and 'guide' or 'back', orientation = 'bm'}, func = 'set_button_pip'}}
}},
{n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.4}, nodes={
    {n=G.UIT.T, config={text = localize('k_jrok_powered'), scale = 0.75*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true, focus_args = {button = G.F_GUIDE and 'guide' or 'back', orientation = 'bm'}, func = 'set_button_pip'}}
}},
{n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.4}, nodes={
    {n=G.UIT.T, config={text = localize('k_by_jrok'), scale = 0.75*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true, focus_args = {button = G.F_GUIDE and 'guide' or 'back', orientation = 'bm'}, func = 'set_button_pip'}}
}}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/UI_definitions.lua'''
pattern = '''
{n=G.UIT.C, config={align = "cm", maxw = 1.4, focus_args = {button = 'start', orientation = 'bm'}, func = 'set_button_pip'}, nodes={
    {n=G.UIT.T, config={text = localize('b_options'), scale = scale, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
}},
'''
position = "at"
payload = '''
{n=G.UIT.R, config={align = "cm", maxw = 1.4, focus_args = {button = 'start', orientation = 'bm'}, func = 'set_button_pip'}, nodes={
    {n=G.UIT.T, config={text = localize('b_options'), scale = scale, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
}},
{n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.4}, nodes={
    {n=G.UIT.T, config={text = localize('k_jrok_powered'), scale = 0.75*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true, focus_args = {button = G.F_GUIDE and 'guide' or 'back', orientation = 'bm'}, func = 'set_button_pip'}}
}},
{n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.4}, nodes={
    {n=G.UIT.T, config={text = localize('k_by_jrok'), scale = 0.75*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true, focus_args = {button = G.F_GUIDE and 'guide' or 'back', orientation = 'bm'}, func = 'set_button_pip'}}
}}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''
if self.area and self.ability.couponed and (self.area == G.shop_jokers or self.area == G.shop_booster) then self.cost = 0 end
'''
position = "after"
payload = '''
if G.GAME.jrok_prompt and JROK.yuri() and (self.config.center_key == "j_blueprint" or self.config.center_key == "j_brainstorm") then
    self.cost = G.GAME.dollars - G.GAME.bankrupt_at + 1
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''engine/controller.lua'''
pattern = '''
if G.STAGE == G.STAGES.RUN then G.FUNCS.start_setup_run() end
'''
position = "before"
payload = '''
G.forced_prompt = G.GAME.jrok_prompt
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''engine/controller.lua'''
pattern = '''
if G.STAGE == G.STAGES.RUN then G.FUNCS.start_setup_run() end
'''
position = "after"
payload = '''
G.forced_prompt = nil
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/button_callbacks.lua'''
pattern = '''
G.FUNCS.start_run(e, {stake = _stake, seed = _seed, challenge = _challenge})
'''
position = "at"
payload = '''
local _prompt = G.forced_prompt or nil
G.FUNCS.start_run(e, {stake = _stake, seed = _seed, challenge = _challenge, prompt = _prompt})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''game.lua'''
pattern = '''
self.GAME = saveTable and saveTable.GAME or self:init_game_object()
'''
position = "after"
payload = '''
G.GAME.jrok_prompt = G.GAME.jrok_prompt or string.lower(JROK.prompt_text) or args.prompt
'''
match_indent = true

# Monstro's Lung
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)"
position = 'before'
match_indent = true
payload = '''
SMODS.calculate_context({jrok_determine_hand = true, full_hand = G.play.cards, scoring_hand = scoring_hand, in_scoring = true, ignore_other_debuff = true}, effects)
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "create_UIBox_round_scores_row('poker_hand'),"
position = 'after'
match_indent = true
payload = '''
create_UIBox_round_scores_row('jrok_gallons', G.C.BLUE),
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "local label_w, score_w, h = ({hand=true,poker_hand=true})[score] and 3.5 or 2.9, ({hand=true,poker_hand=true})[score] and 3.5 or 1, 0.5"
position = 'at'
match_indent = true
payload = '''
local label_w, score_w, h = ({hand=true,poker_hand=true,jrok_gallons=true,})[score] and 3.5 or 2.9, ({hand=true,poker_hand=true,jrok_gallons=true,})[score] and 3.5 or 1, 0.5
'''

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "spot.config.object = Jimbo"
position = 'after'
match_indent = true
payload = '''
Jimbo.states.collide.can = true
Jimbo.states.click.can = true
function Jimbo:click()
	Card_Character.click(self)
    local res = math.random()
    if res < 0.5 then
        love.system.openURL(JROK.feedback_pool[math.random(#JROK.feedback_pool)])
    else
	    G.FUNCS.jrok_feedback_prompt()
    end
end
'''